import {
  GeneratedPageObjectFile,
  GeneratedSpecFile,
  PageObjectGetterDefinition,
  PlaywrightCodegenOutput,
  StepLocatorMapping,
  TestPlanIR,
} from '@qa-automater/types';
import { mapLocatorToPlaywright } from './playwright-code-mapper';

export interface PageObjectGeneratorOptions {
  pageName?: string;
  className?: string;
  fileName?: string;
  specFileName?: string;
  routePath?: string;
}

export class PageObjectGenerator {
  /**
   * Generates a Page Object class file (AC1) and a Playwright test spec file (AC2)
   * from an approved TestPlanIR and StepLocatorMapping array.
   */
  public generate(
    testPlan: TestPlanIR,
    mappings: StepLocatorMapping[],
    options?: PageObjectGeneratorOptions,
  ): PlaywrightCodegenOutput {
    const rawPageName = options?.pageName || options?.className || this.derivePageName(testPlan);
    const className = this.sanitizeClassName(rawPageName);
    const poFileName = options?.fileName || `${className}.page.ts`;
    const poFilePath = `pages/${poFileName}`;

    const getters: PageObjectGetterDefinition[] = [];
    const getterStatements: string[] = [];
    const usedGetterNames = new Set<string>();

    for (let i = 0; i < testPlan.steps.length; i++) {
      const step = testPlan.steps[i];
      if (!step) continue;

      const mapping = mappings.find((m) => m.step_order === i + 1 || m.step_id === step.step_id);
      const chosen = mapping?.chosen_locator || mapping?.candidates?.[0]?.primary_candidate;

      const getterName = this.generateGetterName(
        step.target_description,
        step.action,
        usedGetterNames,
      );
      usedGetterNames.add(getterName);

      const playwrightCode = chosen
        ? chosen.playwright_code || mapLocatorToPlaywright(chosen.strategy, chosen.value)
        : `page.locator('[data-target="${this.escapeString(step.target_description)}"]')`;

      const poPlaywrightCode = playwrightCode.startsWith('page.')
        ? `this.${playwrightCode}`
        : `this.page.locator('${this.escapeString(playwrightCode)}')`;

      getters.push({
        name: getterName,
        playwright_code: playwrightCode,
        target_description: step.target_description,
        step_order: i + 1,
      });

      getterStatements.push(
        `  /**\n   * ${step.target_description}\n   */\n  get ${getterName}(): Locator {\n    return ${poPlaywrightCode};\n  }`,
      );
    }

    const pageObjectContent = [
      `import { Page, Locator } from '@playwright/test';`,
      ``,
      `/**`,
      ` * Page Object Model for ${className}.`,
      ` * Generated by QA Automater Codegen Engine.`,
      ` */`,
      `export class ${className} {`,
      `  readonly page: Page;`,
      ``,
      `  constructor(page: Page) {`,
      `    this.page = page;`,
      `  }`,
      ``,
      getterStatements.join('\n\n'),
      `}`,
      ``,
    ].join('\n');

    const pageObjectFile: GeneratedPageObjectFile = {
      className,
      fileName: poFileName,
      filePath: poFilePath,
      content: pageObjectContent,
      getters,
    };

    // AC2: Spec file generation without hardcoded selectors
    const specFile = this.generateSpecFile(testPlan, pageObjectFile, options);

    return {
      pageObjects: [pageObjectFile],
      specFile,
    };
  }

  private generateSpecFile(
    testPlan: TestPlanIR,
    poFile: GeneratedPageObjectFile,
    options?: PageObjectGeneratorOptions,
  ): GeneratedSpecFile {
    const className = poFile.className;
    const poVarName = className.charAt(0).toLowerCase() + className.slice(1);
    const specFileName =
      options?.specFileName || `${this.toKebabCase(testPlan.title || 'test-suite')}.spec.ts`;
    const specFilePath = `tests/${specFileName}`;

    const routePath = options?.routePath || testPlan.steps[0]?.page_hint || '/';

    const testStatements: string[] = [];

    // Initial navigation
    testStatements.push(`    await ${poVarName}.page.goto('${routePath}');`);

    for (let i = 0; i < testPlan.steps.length; i++) {
      const step = testPlan.steps[i];
      const getter = poFile.getters.find((g) => g.step_order === i + 1);
      if (!step || !getter) continue;

      const getterRef = `${poVarName}.${getter.name}`;

      switch (step.action) {
        case 'fill': {
          const fillValue = step.value || `test-data-${i + 1}`;
          testStatements.push(`    await ${getterRef}.fill('${this.escapeString(fillValue)}');`);
          if (
            step.expected_outcome &&
            /populated|filled|entered|value/i.test(step.expected_outcome)
          ) {
            testStatements.push(
              `    await expect(${getterRef}).toHaveValue('${this.escapeString(fillValue)}');`,
            );
          }
          break;
        }

        case 'click': {
          testStatements.push(`    await ${getterRef}.click();`);
          const urlMatch = step.expected_outcome?.match(/(\/[a-zA-Z0-9_/-]+)/);
          if (urlMatch && urlMatch[1]) {
            testStatements.push(`    await expect(${poVarName}.page).toHaveURL('${urlMatch[1]}');`);
          }
          break;
        }

        case 'navigate': {
          const navUrl = step.value || step.page_hint || routePath;
          testStatements.push(`    await ${poVarName}.page.goto('${navUrl}');`);
          break;
        }

        case 'wait': {
          testStatements.push(`    await expect(${getterRef}).toBeVisible();`);
          break;
        }

        case 'assert':
        default: {
          const urlMatch = step.expected_outcome?.match(/(\/[a-zA-Z0-9_/-]+)/);
          if (urlMatch && urlMatch[1]) {
            testStatements.push(`    await expect(${poVarName}.page).toHaveURL('${urlMatch[1]}');`);
          } else if (
            step.expected_outcome &&
            /text|header|title|heading|label/i.test(step.expected_outcome)
          ) {
            const textMatch = step.expected_outcome.match(/'([^']+)'|"([^"]+)"/);
            const extractedText = textMatch ? textMatch[1] || textMatch[2] : undefined;
            if (extractedText) {
              testStatements.push(
                `    await expect(${getterRef}).toContainText('${this.escapeString(extractedText)}');`,
              );
            } else {
              testStatements.push(`    await expect(${getterRef}).toBeVisible();`);
            }
          } else {
            testStatements.push(`    await expect(${getterRef}).toBeVisible();`);
          }
          break;
        }
      }
    }

    const suiteName = testPlan.title || 'Automated Acceptance Suite';

    const specContent = [
      `import { test, expect } from '@playwright/test';`,
      `import { ${className} } from '../pages/${className}.page';`,
      ``,
      `/**`,
      ` * ${testPlan.title}`,
      ` * ${testPlan.summary || 'Generated Playwright spec using Page Object Pattern'}`,
      ` */`,

      `test.describe('${suiteName}', () => {`,
      `  test('execute user story acceptance flow', async ({ page }) => {`,
      `    const ${poVarName} = new ${className}(page);`,
      ``,
      testStatements.join('\n'),
      `  });`,
      `});`,
      ``,
    ].join('\n');

    return {
      fileName: specFileName,
      filePath: specFilePath,
      content: specContent,
      pageObjectImports: [className],
    };
  }

  private generateGetterName(description: string, action: string, usedNames: Set<string>): string {
    let clean = description
      .toLowerCase()
      .replace(
        /\b(enter|input|type|click|select|press|assert|check|verify|user|the|a|an|button|field|page)\b/g,
        '',
      )
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .trim();

    if (!clean) {
      clean = description
        .toLowerCase()
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .trim();
    }

    const words = clean.split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      words.push('element');
    }

    let camelName = words
      .map((w, index) => (index === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
      .join('');

    // Append semantic suffix based on step action if not already ending with suffix
    if (action === 'fill' && !/Input$|Field$/i.test(camelName)) {
      camelName += 'Input';
    } else if (action === 'click' && !/Button$|Btn$|Link$|Submit$/i.test(camelName)) {
      camelName += 'Button';
    } else if (action === 'assert' && !/Element$|Header$|Title$|Msg$|Card$/i.test(camelName)) {
      camelName += 'Element';
    }

    let finalName = camelName;
    let counter = 1;
    while (usedNames.has(finalName)) {
      finalName = `${camelName}${counter++}`;
    }

    return finalName;
  }

  private derivePageName(testPlan: TestPlanIR): string {
    const hint = testPlan.steps[0]?.page_hint;
    if (hint) {
      const clean = hint.replace(/^\//, '').replace(/[^a-zA-Z0-9]/g, ' ');
      if (clean.trim()) {
        const capitalized = clean
          .split(/\s+/)
          .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
          .join('');
        return `${capitalized}Page`;
      }
    }

    if (testPlan.title) {
      const cleanTitle = testPlan.title.replace(/[^a-zA-Z0-9]/g, ' ');
      const firstWord = cleanTitle.trim().split(/\s+/)[0];
      if (firstWord) {
        return `${firstWord.charAt(0).toUpperCase() + firstWord.slice(1)}Page`;
      }
    }

    return 'LoginPage';
  }

  private sanitizeClassName(name: string): string {
    const clean = name.replace(/[^a-zA-Z0-9]/g, '');
    const capitalized = clean.charAt(0).toUpperCase() + clean.slice(1);
    return capitalized.endsWith('Page') ? capitalized : `${capitalized}Page`;
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9\s_-]/g, '')
      .trim()
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  private escapeString(val: string): string {
    return val.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }
}

export const defaultPageObjectGenerator = new PageObjectGenerator();

export function generatePlaywrightTestSuite(
  testPlan: TestPlanIR,
  mappings: StepLocatorMapping[],
  options?: PageObjectGeneratorOptions,
): PlaywrightCodegenOutput {
  return defaultPageObjectGenerator.generate(testPlan, mappings, options);
}
