import JSZip from 'jszip';
import { sanitizeArtifactCredentials, generateEnvExamplePlaceholder } from './index';

export interface ZipFileEntry {
  path: string;
  content: string | Buffer;
}

export interface ZipArchiveOptions {
  specFiles: Array<{ filename: string; content: string }>;
  pageObjectFiles: Array<{ filename: string; content: string }>;
  readmeContent?: string;
  envExampleContent?: string;
}

/**
 * Story E12.2 AC2: Bundles generated spec files, Page Object files, README.qa-automater.md, and .env.example into a ZIP archive.
 */
export async function createTestZipArchive(options: ZipArchiveOptions): Promise<Buffer> {
  const zip = new JSZip();

  // 1. Add spec files under tests/specs/
  for (const spec of options.specFiles) {
    const sanitized = sanitizeArtifactCredentials(spec.content);
    const cleanFilename = spec.filename.startsWith('tests/specs/')
      ? spec.filename
      : `tests/specs/${spec.filename.replace(/^\/+/, '')}`;
    zip.file(cleanFilename, sanitized);
  }

  // 2. Add Page Object files under tests/page-objects/
  for (const po of options.pageObjectFiles) {
    const sanitized = sanitizeArtifactCredentials(po.content);
    const cleanFilename = po.filename.startsWith('tests/page-objects/')
      ? po.filename
      : `tests/page-objects/${po.filename.replace(/^\/+/, '')}`;
    zip.file(cleanFilename, sanitized);
  }

  // 3. Add README.qa-automater.md
  const readme = options.readmeContent || generateDefaultReadmeWalkthrough(options);
  zip.file('README.qa-automater.md', sanitizeArtifactCredentials(readme));

  // 4. Add .env.example with placeholders
  const envExample = options.envExampleContent || generateEnvExamplePlaceholder();
  zip.file('.env.example', envExample);

  // Generate node Buffer
  const archiveBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return archiveBuffer;
}

/**
 * Generates a default README walkthrough file for extracted ZIP packages.
 */
export function generateDefaultReadmeWalkthrough(options: ZipArchiveOptions): string {
  const specNames = options.specFiles.map((s) => `- \`${s.filename}\``).join('\n') || '- None';
  const poNames = options.pageObjectFiles.map((p) => `- \`${p.filename}\``).join('\n') || '- None';

  return `# 🧪 QA Automater - Generated Playwright Test Package

This archive contains executable Playwright e2e test specs and Page Object classes generated by **QA Automater**.

---

## 📁 Package Contents

### 📄 Playwright Test Specs (\`tests/specs/\`)
${specNames}

### 🧩 Page Object Models (\`tests/page-objects/\`)
${poNames}

### ⚙️ Environment Configuration
- \`.env.example\` - Placeholder environment template (all secrets redacted).

---

## 🚀 Running Tests locally

1. **Install Playwright & Dependencies**:
   \`\`\`bash
   pnpm add -D @playwright/test typescript
   npx playwright install --with-deps
   \`\`\`

2. **Configure Environment Variables**:
   \`\`\`bash
   cp .env.example .env
   # Update .env with target application URL and credentials
   \`\`\`

3. **Execute Playwright Test Suite**:
   \`\`\`bash
   npx playwright test
   \`\`\`
`;
}
